### ISSUE TITLE
Psalm not installed error

### ISSUE THREAD

**Issue by designermonkey** [psalm/psalm-vscode-plugin#104]
I work on many projects with different languages, yet every time I work on a project that does not use PHP and have psalm installed in a vendor project folder I get an error.

Would it be possible to look for psalm in fallback folders?

```
./vendor/bin/psalm-language-server
./bin/psalm-language-server
../vendor/bin/psalm-language-server
../bin/psalm-language-server
~/.composer/vendor/bin/psalm-language-server
~/.composer/bin/psalm-language-server
```

Or, if there is no composer.json file in the current folder, look at the user home folder file?

**Comment by designermonkey** [comment]
![Screenshot 2021-09-18 at 13 45 15](https://user-images.githubusercontent.com/221344/133889447-1d6e932d-6735-4b27-ad84-802f51f053c1.png)

**Comment by tm1000** [comment]
You can add these paths in the .vscode folder under settings.json for each project

**Comment by designermonkey** [comment]
I've probably muddied two concerns here, so thanks for the response but please actually ignore that request.

The actual issue is that I should not be getting warnings or errors about Psalm for projects that are not using PHP. Maybe there needs to be some code that looks for the presence of a composer.json file in the root. If it's not there turn off any Psalm functionality in the extension.

**Comment by tm1000** [comment]
The plug-in has three activation events: Any php file, any psalm.xml or psalm-dist.xml file. One of those is being met in your project I assume?

Looking for composer.json only works for people using composer. Which is not every user of psalm.

**Comment by designermonkey** [comment]
I have subprojects within this monorepo that have psalm.xml files as they are PHP. I see above that that would cause the issue and didn't realise that's how it was checking.

As the extension is looking for config in a glob path of `**` then would it not make sense to look for a language server at the path where it finds a php file or psalm config?

I've attempted to change the script path setting to `**/vendor/bin/psalm-language-server` and the error still persists as I imagine this is an invalid path.

Is it possible to look for the language server where the config file is first found?

**Comment by tm1000** [comment]
The path to the language server is not a glob, you should be setting `vendor/bin/psalm-language-server`

The issue with this extension randomly trying to find a language server and then using that is that it could be searching vendor folders and finding one that is deeply nested and perhaps an old version. 

Additionally a monorepo is not a good usage of the psalm vscode plugin, the reasoning is that each project in your mono repo could have a different Psalm version and different XML output and furthermore psalm looks at the xml file to know what is the "root" of said project so it would only actually run on one of your monorepos because VScode itself is global against all of your monorepos

**Comment by designermonkey** [comment]
>Additionally a monorepo is not a good usage of the psalm vscode plugin

I'm not trying to use it this way. I'm trying to stop having errors display where there aren't any.

How about this:

```
	"activationEvents": [
		"onLanguage:php",
		"workspaceContains:./psalm.@(xml|xml.dist)"
	],
```

As the psalm config needs to be at the root of the project, this makes most sense.

**Comment by designermonkey** [comment]
I thought I was being quite polite about all this, but from the tone of your last message, I think I shan't bother!

> but what you keep requesting

I don't keep requesting, I've made one request and I thought I was in a discussion to find a possible answer.

> As I have told you numerous times before not everyone (including me!) has psalm in their root directory

Theres no need to get short about this, as you didn't actually state that at all, you said about `composer.json`. I'm just trying to come up with any possible solution.

I think I'll close this and not use your exension.

**Comment by tm1000** [comment]
Hi there

Please remember this is all text based communication. You can't actually see or hear the tone on my voice or what I am thinking. 

I'm not trying to be short. I'm trying to come to a solution together that will work for the community as a whole not a one off case. 

I thank you for your input thus far. Remember that many open source projects are worked on through a voluntary basis. Like this one. I devote hundreds of my own hours to working on this project in my spare time so it's successful. I don't get paid for any of this. 

Regardless of this falling out I'm s I'll going to come to a solution for you in the near future which will at least suppress these messages

Have a good day and thank you for your contributions! Much appreciated! 😃

**Comment by tncrazvan** [comment]
> You can add these paths in the .vscode folder under settings.json for each project

That feature is not available yet is it? ( https://github.com/microsoft/vscode/issues/2809 )

Until that comes, I've managed to track down a bit of what's happening in the code using a workspace of mine.
The issue seems to be this line https://github.com/psalm/psalm-vscode-plugin/blob/5bb291cf1a4d06291f57b4d155c513af51ff94eb/src/extension.ts#L40

it's picking the first workspace of the bunch, which in my case:
![image](https://user-images.githubusercontent.com/6891346/179397988-48532448-e326-4030-9264-bc3a22420969.png)

results into this:

![image](https://user-images.githubusercontent.com/6891346/179398016-49a1c6e7-4470-42aa-b81a-19b2e161f2f7.png)

and it so happens that project (`catpaw-core`) doesn't have psalm installed and even if it did it wouldn't have the same libraries as the other projects.

I think the cleanest solution is to create a language server for each project.
@tm1000  I'm working on that right now, do you think that's a good idea?

**Comment by tncrazvan** [comment]
@tm1000 or maybe restarting the language server with a different workspace, that seems even better? I'll send a pr soon enough.

**Comment by tm1000** [comment]
@tncrazvan you can add paths without variables. Just use relative paths. It's been working this way for years. Launching multiple language servers seems pretty intensive and the way the io stream works I don't think you can't do this without modifying psalm itself to support multiple workspaces.

**Comment by tncrazvan** [comment]
> Just use relative paths

Do you mean [these](https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables)?

They don't seem to work at least not in my case.
I tried
```json
"psalm.psalmScriptPath": "${fileWorkspaceFolder}/vendor/bin/psalm-language-server"
```

and

```json
"psalm.psalmScriptPath": "${workspaceFolder}/vendor/bin/psalm-language-server"
```

When debugging the extension it looks like those don't get resolved, they just stay the way they are as `${fileWorkspaceFolder}/vendor/bin/psalm-language-server` and `${workspaceFolder}/vendor/bin/psalm-language-server` which results into `Psalm not installed`.

Am I missing something?

**Comment by tm1000** [comment]
That's not a relative path. That's a path with a variable (which isn't supported)

I don't know how your system is setup but relative paths work just fine for me and for plenty of other projects and other extensions

A relative path is just that. Relative to the root. 

`"psalm.psalmScriptPath": "vendor/bin/psalm-language-server"`

At my company we use this all day long as there are about 4-5 of us working on the same project from windows to different variants of Linux on different archs.

**Comment by tncrazvan** [comment]
ok, so this

> `"psalm.psalmScriptPath": "vendor/bin/psalm-language-server"`

at first glance does not work for me.

I think it's because the first project in my workspace does not have psalm installed.

I'll agree with you 100% that someone trying to use psalm should install psalm (duh).

In my case it's been a long time since I worked on that specific workspace and I didn't check if psalm was even installed in all projects, but I made sure it was installed on the actual project I was working on within the workspace.

I say "at first glance" because it's only crashing because that first project is missing psalm, if I install psalm in that first project the language server does start and works properly for all projects.


Do you see where I'm coming from? it should not make all the other projects unable to use psalm, no?

The message error simply says "Psalm no installed", so it's hard to understand what's going on.

---

The pr I sent will make it so it always uses the psalm-language-server relative to the project you're working on.

If the pr is not good, at least the error message should be more specific I think, maybe saying which language-server it's trying to use in which project (I think vscode does provide the names of the projects).

It can be a huge waste of time, I mean it was in my case, granted I might be dumb.

**Comment by tm1000** [comment]
Go ahead and make the PR but this extension does not support workspaces in the way this thread proposes and I don't think it ever will. Essentially you'd need to launch a separate psalm server for every workspace you've got in there and that would end up being crazy on cpu and ram usage. 

If you open up each workspace individually it would work. This is how most people use vscode. Each project is a separate instance of vscode. Then the relative paths work. 

Additionally no idea where you are setting the vscode settings into.

**Comment by tncrazvan** [comment]
> Additionally no idea where you are setting the vscode settings into.

here `$HOME/.config/Code/User/settings.json` or from the ui, is that wrong?

**Comment by tm1000** [comment]
Yes. It's looking in the root of your entire file system for psalm. You normally set the paths per project

**Comment by tncrazvan** [comment]
I've set the path inside the workspace file (the `.code-workspace` file)

The workspace file is the following in my case:

```json
{
	"folders": [
		{
			"name": "catpaw-core",
			"path": "../GitHub/tncrazvan/catpaw-core"
		},
		{
			"name": "catpaw-web",
			"path": "../GitHub/tncrazvan/catpaw-web"
		},
		{
			"name": "catpaw-cli",
			"path": "../GitHub/tncrazvan/catpaw-cli"
		},
		{
			"name": "catpaw-environment",
			"path": "../GitHub/tncrazvan/catpaw-environment"
		},
		{
			"name": "catpaw-examples",
			"path": "../Music/GitHub/tncrazvan/catpaw-examples"
		},
		{
			"name": "catpaw-mysql",
			"path": "../GitHub/tncrazvan/catpaw-mysql"
		},
		{
			"name": "catpaw-raspberrypi",
			"path": "../GitHub/tncrazvan/catpaw-raspberrypi"
		},
		{
			"name": "catpaw-starter",
			"path": "../GitHub/tncrazvan/catpaw-starter"
		},
		{
			"name": "catpaw-store",
			"path": "../GitHub/tncrazvan/catpaw-store"
		},
		{
			"name": "catpaw-svelte-starter",
			"path": "../GitHub/tncrazvan/catpaw-svelte-starter"
		},
		{
			"name": "catpaw-queue",
			"path": "../GitHub/tncrazvan/catpaw-queue"
		}
	],
	"settings": {
	    "psalm.psalmScriptPath": "vendor/bin/psalm-language-server"
	}
}
```
and it's still crashing.

I've tried the same thing at the project level (inside the `.vscode/settings.json` file), still crashing.

I'll go ahead and make the pr, if someone can take a look at it or make a better one that would be nice because having all projects in one workspace like that is really handy especially for code that can't live in a monorepo.

**Comment by tm1000** [comment]
The solution @tncrazvan figured out resolves this issue. Checkout 2.7.0 🥳!
