### ISSUE TITLE
Stuck with "Psalm: starting"

### ISSUE THREAD

**Issue by frnnds** [psalm/psalm-vscode-plugin#64]
I'd downloaded paslm and this extension, and I've stuck with "Psalm: starting" text on the status bar. 

Output says 

```
Scanning files...
Analyzing files...

E
[Error - 12:16:10 PM] Connection to server is erroring. Shutting down server.
```

Psalm is working properly, project has psalm.xml.

**Comment by tm1000** [comment]
Hi there can you tell me a little bit more about your environment? Windows or Linux etc?

**Comment by frnnds** [comment]
Hi. Linux, psalm installed from composer. Psalm version is `4.8.1@f73f2299dbc59a3e6c4d66cff4605176e728ee69`. 

For the testing I've created a simple folder with src folder with one file in it, which contains var_dump function calling, and set psalm level  to the '1'. Psalm from cli successfully found that error.

**Comment by tm1000** [comment]
Theres two versions of Psalm in the VS Code Marketplace because of issues with Marketplace itself. One is version 2.0.3 and one is 1.x can you let me know which version you are running?

If you are running 2.0.2 then upgrade to 2.0.3. I havent updated the 1.x series yet only because I didnt have access to it until last Friday

**Comment by frnnds** [comment]
Yea, thanks, It works.
